# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80963699bb9f9378ab724463219ffc5e740b19ca86c1886c5aad9ef735eee916963b8d1a3df74b5f55577901da3ddac6fdd606607536e83780efae4c701da27e

test:
  secret_key_base: 26263621166054520d75e1bd40087798d0cca875df29caab23bce8e591a054e85b0aa7f8f5985195d6927915af3d4e6b2cf074fa1feb6ede1c34f4651467e5f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
